[package]
name = "rust_texteditor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21.0" #add this dependency
itertools = "0.10.2"
lazy_static = "1.4.0"